#!/usr/bin/env python3
"""Quick gate before committing PCB changes: ERC + DRC + a few sanity checks.

Run from the project root or from this directory. Exits non-zero if anything
that should be checked before fabrication is wrong.
"""
from __future__ import annotations

import csv
import shutil
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parent
SCH = ROOT / "zero3-water-logger-carrier.kicad_sch"
PCB = ROOT / "zero3-water-logger-carrier.kicad_pcb"
CSV_PATH = ROOT / "zero3-water-logger-carrier-pinout.csv"


def find_kicad_cli() -> str:
    on_path = shutil.which("kicad-cli")
    if on_path:
        return on_path
    for candidate in [
        r"C:\Program Files\KiCad\10.0\bin\kicad-cli.exe",
        r"C:\Program Files\KiCad\9.0\bin\kicad-cli.exe",
        "/Applications/KiCad/KiCad.app/Contents/MacOS/kicad-cli",
        "/usr/bin/kicad-cli",
        "/usr/local/bin/kicad-cli",
    ]:
        if Path(candidate).exists():
            return candidate
    sys.exit("error: kicad-cli not found.")


def csv_matches_schematic() -> bool:
    """The pinout CSV is generated by generate_schematic.py; assert it was."""
    if not CSV_PATH.exists():
        print("FAIL: pinout CSV missing.")
        return False
    with CSV_PATH.open() as f:
        rows = list(csv.reader(f))
    if not rows or rows[0] != ["Ref", "Pin", "Pin name", "Net", "Notes"]:
        print(f"FAIL: pinout CSV header is not the auto-generated format. Got: {rows[0] if rows else 'empty'}")
        return False
    print(f"OK: pinout CSV has {len(rows) - 1} pin entries in the generated format.")
    return True


def main() -> int:
    kicad = find_kicad_cli()
    failures = 0

    print("=== Pinout CSV format check ===")
    if not csv_matches_schematic():
        failures += 1

    print("\n=== Schematic ERC ===")
    erc = subprocess.run([kicad, "sch", "erc", str(SCH)], capture_output=True, text=True)
    print(erc.stdout)
    if "Found 0 violations" not in erc.stdout:
        print("FAIL: ERC reports violations.")
        failures += 1

    print("=== PCB DRC (refilling zones) ===")
    drc = subprocess.run(
        [kicad, "pcb", "drc", "--refill-zones", "--save-board", str(PCB)],
        capture_output=True,
        text=True,
    )
    print(drc.stdout)
    if "Found 0 violations" not in drc.stdout:
        print("FAIL: DRC reports violations.")
        failures += 1

    # Unconnected items are tracked, not a hard fail — fabrication readiness
    # requires zero unconnected items, but routing-in-progress states should
    # still be able to run this validator without failing the whole gate.
    for line in drc.stdout.splitlines():
        if "unconnected" in line.lower():
            print(f"NOTE: {line.strip()}")

    if failures:
        print(f"\nvalidate_design.py: {failures} check(s) failed.")
        return 1
    print("\nvalidate_design.py: all checks passed.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
